name: Permissions
version: 0.0.1
description: Fix & Lock down your file & folder permissions
url: https://github.com/jrc9designstudio/statamic-permissions
developer: JRC9 Design Studio
developer_url: https://github.com/jrc9designstudio
